@echo off
rem ***  The first known attempt at MS-DOS adventuring    ***
rem *** Launched by Johbe and Frera on 30:th of March '93 ***

set &room=home
set &o1loc=chest
set &o2loc=rivendell
set &o3loc=gandalf
set &o4loc=home
set &o5loc=woods
set &o6loc=cave
set &o7loc=den
set &stoned=NO

echo Hobbit - The True Story.
echo.
echo An MS-DOS adventure released by Milbus Software (tm) 1993.
echo.
call look

